config/routes.rb
Rails.application.routes.draw do

  mount Payola::Engine => '/payola', as: :payola

  root 'welcome#welcome'

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#delete', as: :sign_out

  get "/users/new" => 'users#new', as: :sign_up
  post "/users/new" => 'users#create', as: :users
  get '/users/:id/feed' => 'users#feed', as: :posts
  get '/users/:id/feed/upload' => 'users#new_post', as: :new_post
  post 'users/:id/feed' => 'users#create_post'
  post 'users/:id/feed' => 'users#create_comment', as: :comments
  get '/users/explore/:id' => 'users#profile', as: :user
  get '/users/explore' => 'users#explore', as: :explore
  post 'users/explore/:id/follow' => 'following#create', as: :follow
  post 'users/explore/:id/unfollow' => 'following#delete', as: :unfollow

  get '/users/:id/orders/index' => 'orders#index', as: :orders
  get '/users/:id/orders/:id' => 'orders#show', as: :order

  get 'posts/:id' => 'posts#show', as: :post
  post '/users/:id/cart' => 'carts#add_to_cart', as: :add_to_cart
  get '/users/:id/cart' => 'carts#view', as: :cart
  delete '/users/:id/cart' => 'carts#remove_from_cart', as: :remove_from_cart

  get '/users/:id/checkout'=>'checkout#start', as: :checkout
  post '/users/:id/checkout'=> 'checkout#process_payment', as: :process_payment
  get '/users/:id/receipt/:id' => 'checkout#receipt', as: :receipt

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def total_price
     order_items.map { |order_item| order_item.total_price }.sum
  end

  def description
   "Order ##{id}. #{order_items.map {|oi| oi.post.name}.join(", ")}"
  end
  
  def total_price_in_cents
    (total_price * 100).to_i
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :post

  def total_price
    quantity * price 
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  attachment :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :orders
  has_many :comments
  acts_as_followable
  acts_as_follower
  attachment :photo
  has_secure_password
  validates :first_name, :last_name, :user_name, :email, :password, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action do
      if @current_user.nil?
        redirect_to sign_in_path
      end
    end

    def remove_from_cart
      order = Order.find_by status: 'cart', user_id: @current_user.id
      @post = Post.find_by id: params[:post_id]

      order_item = OrderItem.find_by order_id: order.id, post_id: @post.id
      order_item.destroy

      redirect_to cart_path
    end

    def add_to_cart


      @post = Post.find_by id: params[:post_id]

      order = Order.find_by status: 'cart', user_id: @current_user.id

      if order.nil?
        order = Order.new
        order.user = @current_user
        order.save!
      end

      order_item = OrderItem.find_by order_id: order.id, post_id: @post.id
      if order_item.present?
        order_item.quantity = order_item.quantity + 1
      else
        order_item = OrderItem.new
        order_item.order = order
        order_item.post = @post # what do I replace this with? It's nil
        order_item.price = @post.price
        order_item.shipping_cost = 0
        order_item.quantity = 1
      end
      order_item.save!
      redirect_to cart_path

    end

    def view

      @order = Order.find_by status: 'cart', user_id: @current_user.id
    end
  end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action do
      if @current_user.nil?
        redirect_to sign_in_path
      end
    end

    def start
      @order = Order.find_by status: 'cart', user_id: @current_user.id
    end

    def process_payment
      @order = Order.find_by status: 'cart', user_id: @current_user.id
      @user=User.first
      card_token = params[:stripeToken]

      Stripe.api_key = "sk_test_xIGhTi9JGwC0H65Tq1KdFEJE"

      Stripe::Charge.create(
        :amount => @order.total_price_in_cents,
        :currency => "usd",
        :source => card_token,
        :description => @order.description
      )

      if @order.update status: 'pending'
        InstructionsMailer.instructions_email(@user).deliver
      redirect_to receipt_path(id: @order.id)
      else
        render :new
      end
    end

    def receipt
      @order = Order.find_by! id: params[:id], user_id: @current_user.id
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where("status !=?", 'cart')
  end

  def show
    @order = Order.find_by id: params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def feed
    @post=Post.new
    @user= User.find_by id: params[:id]
    @current_user = User.find_by id: session[:user_id]
    @users=User.all
    if @current_user && @current_user.following_users.present?
    follower_ids = @current_user.following_users.pluck(:id)
    all_ids = follower_ids << @current_user.id
    @posts = Post.where(user_id: all_ids).order("created_at DESC")
  else
    @posts = Post.all.order("created_at desc")
  end
  end

  def new_post
@post=Post.new
end

def create_post
  @post = Post.new params.require(:post).permit(:description,:user_id, :view_count, :culture, :type, :location, :photo, :name, :price,:delivery_cost, :inventory)
  @post.user=@current_user
  if @post.save
    redirect_to posts_path(id: @current_user.id)
  else
    flash.now[:alert] = "Looks like your Missing Something"
    render :new
  end
end

  def profile
    @user= User.find_by id: params[:id]
    @posts=Post.all
  end

  def new
  end

  def explore
    @user= User.find_by id: params[:id]
    @posts=Post.all
  end

  def new
  @user=User.new
  end

  def create
  @user = User.new params.require(:user).permit(:email, :password, :first_name, :last_name, :user_name, :city, :address, :photo)
  if @user.save
   session[:user_id] = @user.id
  redirect_to posts_path(id: @user.id)
  else
   flash.now[:alert] = "Something is Missing"
  render:new
  end
  end

  def create_comment
    @post = Post.find_by id: params[:id]
    @comment = Comment.new params.require(:comment).permit(:comment)
    @comment.post_id = @post.id

    if @comment.save
      redirect_to explore_path
    else
      render :view
    end
  end


  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/checkout/receipt.html.erb
<nav id="navfeed">

  <div class="feed-title"><strong>Savorit</strong>
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
  <center>  <%= link_to posts_path(id: @current_user.id) do %><i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
  <center> <%= link_to explore_path do%><i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center> <%= link_to new_post_path(id: @current_user.id) do %><i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
  <center>   <%= link_to cart_path(id: @current_user.id) do %><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

    <div class="icons">
      <center> <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
    </div>
</div>

<h1> RECEIPT </h1>
<ul>
  <li>
    Order ID: <%= @order.id %>
  </li>
  <li>
    Purchaser: <%= @order.user.first_name %> <%= @order.user.last_name %> | <%= @order.user.email %>
  </li>
  <li>
    Total Price:

    <%= @order.total_price %>
  </li>
</ul>

<p id="receipthead"><strong>Items</strong></p>
<div class="receiptitems">
<% @order.order_items.each do |f| %>
<%= f.post.name %>
<%= f.quantity %> at <%= f.price %>
<p>
Total Price:  <%= number_to_currency f.total_price %>
</p>
<%end %>
</div>

app/views/checkout/start.html.erb
<nav id="navfeed">

  <div class="feed-title"><strong>Savorit</strong>
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
  <center>  <%= link_to posts_path(id: @current_user.id) do %><i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
  <center> <%= link_to explore_path do%><i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center> <%= link_to new_post_path(id: @current_user.id) do %><i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
  <center>   <%= link_to cart_path(id: @current_user.id) do %><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

    <div class="icons">
      <center> <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
    </div>
</div>

<center><h2>One last step before FEASTING</h2></center>

<center><%= form_tag process_payment_path, method: :post, id: "payment-form" do %>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_UQ02f5WGJ1E2k2sUXLJcqn4C"
    data-name="Savorit"
    data-description="<%= @order.description %>"
    data-amount="<%= @order.total_price_in_cents %>"
    data-email="<%= @current_user.email %>"
    data-shipping-address="true"
    data-locale="auto">
  </script>
<% end %>

<% if false %>
<%= form_tag process_payment_path, method: :post, id: "payment-form" do %>

  <span class="payment-errors"></span>

  <div class="">
    <%= label_tag :credit_card_number %>
    <%= text_field_tag :credit_card_number, "", class: "card-number" %>
  </div>

  <div class="">
    <%= label_tag :expiration_month %>
    <%= select_month Date.today, {}, class: "card-expiry-month" %>
  </div>

  <div class="">
    <%= label_tag :expiration_year %>
    <%= select_year Date.today, {start_year: Date.today.year, end_year: Date.today.year+20}, class: "card-expiry-year" %>
  </div>

  <div class="">
    <%= label_tag :cvc %>
    <%= number_field_tag :cvc, "",class: "card-cvc"%>
  </div>

  <div class="">
    <%= label_tag :token %>
    <%= text_field_tag :token, "", class: "card-token" %>
  </div>

  <%= submit_tag '$$$Buy$$$', class: :btn %>

<% end %>

<% end %>
</center>

<center><h3>Your Items</h3></center>


<center>
<table>
  <thead>
    <tr>
      <th>
        Item
      </th>
      <th>
        Quantity
      </th>
      <th>
        Per Item Price
      </th>
      <th>
        Total Price
      </th>
    </tr>
  </thead>

<tbody>
    <% @order.order_items.each do |order_item| %>

    <tr>
      <td>
        <%= order_item.post.name %>
      </td>
      <td>
        <%= order_item.quantity %>
      </td>
      <td>
        <%= order_item.price %>
      </td>
      <td>
        <%= number_to_currency order_item.total_price %>
      </td>
    </tr>

    <% end %>

  </tbody>
</table>
</center>