config/routes.rb
Rails.application.routes.draw do

  mount Payola::Engine => '/payola', as: :payola

  root 'welcome#welcome'

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#delete', as: :sign_out

  get "/users/new" => 'users#new', as: :sign_up
  post "/users/new" => 'users#create', as: :users
  get '/users/:id/feed' => 'users#feed', as: :posts
  get '/users/:id/feed/upload' => 'users#new_post', as: :new_post
  post 'users/:id/feed' => 'users#create_post'
  post 'users/:id/feed' => 'users#create_comment', as: :comments
  get '/users/explore/:id' => 'users#profile', as: :user
  get '/users/explore' => 'users#explore', as: :explore
  post 'users/explore/:id/follow' => 'following#create', as: :follow
  post 'users/explore/:id/unfollow' => 'following#delete', as: :unfollow

  get '/users/:id/orders/index' => 'orders#index', as: :orders
  get '/users/:id/orders/:id' => 'orders#show', as: :order

  get 'posts/:id' => 'posts#show', as: :post
  post '/users/:id/cart' => 'carts#add_to_cart', as: :add_to_cart
  get '/users/:id/cart' => 'carts#view', as: :cart
  delete '/users/:id/cart' => 'carts#remove_from_cart', as: :remove_from_cart

  get '/users/:id/checkout'=>'checkout#start', as: :checkout
  post '/users/:id/checkout'=> 'checkout#process_payment', as: :process_payment
  get '/users/:id/receipt/:id' => 'checkout#receipt', as: :receipt

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def total_price
     order_items.map { |order_item| order_item.total_price }.sum
  end

  def description
   "Order ##{id}. #{order_items.map {|oi| oi.post.name}.join(", ")}"
  end
  
  def total_price_in_cents
    (total_price * 100).to_i
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :post

  def total_price
    quantity * price 
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  attachment :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :orders
  has_many :comments
  acts_as_followable
  acts_as_follower
  attachment :photo
  has_secure_password
  validates :first_name, :last_name, :user_name, :email, :password, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action do
      if @current_user.nil?
        redirect_to sign_in_path
      end
    end

    def remove_from_cart
      order = Order.find_by status: 'cart', user_id: @current_user.id
      @post = Post.find_by id: params[:post_id]

      order_item = OrderItem.find_by order_id: order.id, post_id: @post.id
      order_item.destroy

      redirect_to cart_path
    end

    def add_to_cart


      @post = Post.find_by id: params[:post_id]

      order = Order.find_by status: 'cart', user_id: @current_user.id

      if order.nil?
        order = Order.new
        order.user = @current_user
        order.save!
      end

      order_item = OrderItem.find_by order_id: order.id, post_id: @post.id
      if order_item.present?
        order_item.quantity = order_item.quantity + 1
      else
        order_item = OrderItem.new
        order_item.order = order
        order_item.post = @post # what do I replace this with? It's nil
        order_item.price = @post.price
        order_item.shipping_cost = 0
        order_item.quantity = 1
      end
      order_item.save!
      redirect_to cart_path

    end

    def view

      @order = Order.find_by status: 'cart', user_id: @current_user.id
    end
  end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action do
      if @current_user.nil?
        redirect_to sign_in_path
      end
    end

    def start
      @order = Order.find_by status: 'cart', user_id: @current_user.id
    end

    def process_payment
      @order = Order.find_by status: 'cart', user_id: @current_user.id
      @user=User.first
      card_token = params[:stripeToken]

      Stripe.api_key = "sk_test_xIGhTi9JGwC0H65Tq1KdFEJE"

      Stripe::Charge.create(
        :amount => @order.total_price_in_cents,
        :currency => "usd",
        :source => card_token,
        :description => @order.description
      )

      if @order.update status: 'pending'
        InstructionsMailer.instructions_email(@user).deliver
      redirect_to receipt_path(id: @order.id)
      else
        render :new
      end
    end

    def receipt
      @order = Order.find_by! id: params[:id], user_id: @current_user.id
    end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def create
  new_user = User.find_by(id: params[:id])
    @current_user.follow new_user
    redirect_to user_path(id: new_user.id)
end

def delete
  new_user = User.find_by(id: params[:id])
  @current_user.stop_following new_user
  redirect_to user_path(id: new_user.id)
end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where("status !=?", 'cart')
  end

  def show
    @order = Order.find_by id: params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    email = params[:email]
    password = params[:password]
    user = User.find_by email: email
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to posts_path(id: user.id)
    else
      render :new
  end
end

def delete
  session[:user_id] = nil
    redirect_to root_path
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def feed
    @post=Post.new
    @user= User.find_by id: params[:id]
    @current_user = User.find_by id: session[:user_id]
    @users=User.all
    if @current_user && @current_user.following_users.present?
    follower_ids = @current_user.following_users.pluck(:id)
    all_ids = follower_ids << @current_user.id
    @posts = Post.where(user_id: all_ids).order("created_at DESC")
  else
    @posts = Post.all.order("created_at desc")
  end
  end

  def new_post
@post=Post.new
end

def create_post
  @post = Post.new params.require(:post).permit(:description,:user_id, :view_count, :culture, :type, :location, :photo, :name, :price,:delivery_cost, :inventory)
  @post.user=@current_user
  if @post.save
    redirect_to posts_path(id: @current_user.id)
  else
    flash.now[:alert] = "Looks like your Missing Something"
    render :new
  end
end

  def profile
    @user= User.find_by id: params[:id]
    @posts=Post.all
  end

  def new
  end

  def explore
    @user= User.find_by id: params[:id]
    @posts=Post.all
  end

  def new
  @user=User.new
  end

  def create
  @user = User.new params.require(:user).permit(:email, :password, :first_name, :last_name, :user_name, :city, :address, :photo)
  if @user.save
   session[:user_id] = @user.id
  redirect_to posts_path(id: @user.id)
  else
   flash.now[:alert] = "Something is Missing"
  render:new
  end
  end

  def create_comment
    @post = Post.find_by id: params[:id]
    @comment = Comment.new params.require(:comment).permit(:comment)
    @comment.post_id = @post.id

    if @comment.save
      redirect_to explore_path
    else
      render :view
    end
  end


  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/orders/index.html.erb
<table>
  <thead>
    <tr>
      <th>
        Order ID
      </th>
      <th>
        username
      </th>
      <th>
        Total Price
      </th>
    </tr>
  </thead>
</table>
<tbody>
  <% @orders.each do |f| %>
  <tr>
    <td>
      <%= f.id %>
    </td>
    <td>
      <%= f.user.first_name %> <%= f.user.last_name %>
    </td>
    <td>
<%= number_to_currency @order.total_price%>
    </td>
    <td>
      <%= link_to "Order #{order.id}", order_path(id: order.id) %>
    </td>
  </tr>
  <%end%>
</tbody>

app/views/orders/show.html.erb
<%= order.id %>
<ul>
  <li>
    Purchase Date : <%= @order.purchased_at %>
  </li>
  <li>
    Order ID: <%= @order.id %>
  </li>
  <li>
    Purchaser: <%= @order.user.first_name %> <%= @order.user.last_name %> | <%= @order.user.email %>
  </li>
  <li>
    Total Price:

    <%= @order.total_price %>
  </li>
</ul>

Items
<% @order.order_items.each do |f| %>
<%= f.post.name %>
<%= f.quantity %> at <%= f.price %>
<p>
Total Price:  <%= number_to_currency f.total_price %>
</p>
<%end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/explore.html.erb
<nav id="navfeed">

  <div class="feed-title">
    Savor it
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
    <center>
      <%= link_to posts_path(id: @current_user.id) do %>
      <i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to explore_path do%>
      <i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to new_post_path(id: @current_user.id) do %>
      <i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to cart_path(id: @current_user.id) do %>
      <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
  </div>
</div>
<div class="explore-image-container">
<%= image_tag 'hopdoddy2.jpg', class:'explore-image' %>
  <p class="explore-image-text">
    <i class="fa fa-search" aria-hidden="true"></i> Food You Might Like
  </p>
</div>
<div class="explorecontainer">
  <% @posts.each do |f|%>
  <div class="explorepic">
      <%= link_to user_path(id: f.user) do%><%= image_tag attachment_url(f, :photo, :fill, 300, 300, format: "jpg") %><%end%>
    </div>
    <%end %>
  </div>

app/views/users/feed.html.erb
<nav id="navfeed">

  <div class="feed-title">Savor it
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
  <center>  <%= link_to posts_path(id: @current_user.id) do %><i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
  <center> <%= link_to explore_path do%><i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center> <%= link_to new_post_path(id: @current_user.id) do %><i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
  <center>   <%= link_to cart_path(id: @current_user.id) do %><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

    <div class="icons">
      <center> <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
    </div>
</div>

<div class="container">
    <% @posts.each do |f|%>
    <div class="feedpiccontainer">
      <div class="feedpicheader">
        <p><%= link_to user_path(id: f.user) do%><%= image_tag attachment_url(f.user, :photo, :fill, 50, 50, format: "jpg"), class:"pp" %><%end%>
          <%= f.user.first_name %>
          <%= f.user.last_name %>
          <%=link_to 'Eat Me', add_to_cart_path(post_id: f.id), class:"buy", method: :post %>
        </p>
    </div>
    <div class="picdiv">
      <%= image_tag attachment_url(f, :photo, :fill, 600,800, format: "jpg"), class:"feedpic" %>
  </div>
  <div class="feedpicfooter">
      <p><%= f.description%></p>
      <p>This is the <%= f.name %> at <%= f.location %></p>
      <p>culture:<%= f.culture %></p>
  </div>
    <%end %>
</div>
</div>

app/views/users/new.html.erb
<div class="signuppage">
    <% if @user.errors.any? %>
      <%= pluralize(@user.errors.count, 'error') %> prevented your form from success.
      <ul class="mdl-list">
        <% @user.errors.full_messages.each do |msg| %>
          <li class="errorsss"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <center><p id="join">Savor it</p></center>
    <center><p id="welcomeback"> Join Today </p></center>
      <%= form_for @user do |f| %>
      <center><div class="">
        <%= f.label :first_name, class:"signinheader" %>
        <%= f.text_field :first_name, placeholder:"Name", class:'signinform' %>
      </div></center>
      <center><div class="">
        <%= f.label :last_name, class:"signinheader" %>
        <%= f.text_field :last_name,placeholder:"User Name", class:'signinform' %>
      </div></center>
      <center><div class="">
        <%= f.label :user_name, class:"signinheader" %>
        <%= f.text_field :user_name,placeholder:"User Name", class:'signinform' %>
      </div></center>
      <center><div class="">
        <%= f.label :email, class:"signinheader" %>
        <%= f.text_field :email, placeholder:"Email", class:'signinform'%>
      </div></center>
       <center><div class="">
          <%= f.label :password, class:"signinheader" %>
          <%= f.password_field :password, placeholder:"Password", class:'signinform' %>
        </div></center>

        <center><div class="attachmentfield">
          <%= f.label :photo, class:"signinheader" %>
          <%= f.attachment_field :photo, class:'signinform' %>
        </div></center>

        <center><div class="attachmentfield">
          <%= f.label :address, class:"signinheader" %>
          <%= f.text_field :address, class:'signinform' %>
        </div></center>

      <center>  <div>
        <%= f.submit "Sign Up", class: "signinlink" %>
          <% end %>
        </div></center>
      </div>

app/views/users/new_post.html.erb
<nav id="navfeed">

  <div class="feed-title">
    Savor it
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
    <center>
      <%= link_to posts_path(id: @current_user.id) do %>
      <i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to explore_path do%>
      <i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to new_post_path(id: @current_user.id) do %>
      <i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to cart_path(id: @current_user.id) do %>
      <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

  <div class="icons">
    <center>
      <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
  </div>
</div>

<div class="edit_container">
  <div id="image-cropper">
    ​
    <div class="image-editor">
      <center>
        <div class="fileUpload">
          <span>
            Upload
          </span>
          <input type="file" class="cropit-image-input">
        </div>
        <div class="cropit-preview"></div>
        <div class="image-size-label">
          Resize image
        </div>
        <input type="range" class="cropit-image-zoom-input">
        <button class="rotate-ccw">
          <i class="fa fa-undo fa-2x" aria-hidden="true"></i>
        </button>
        <button class="rotate-cw">
          <i class="fa fa-repeat fa-2x" aria-hidden="true"></i>
        </button>
        <center></div>
      </div>

      <div class="imageform">
        <p>
          Let them know the details
        </p>
          <form action="#" method="post" name="form_name" id="form_id" class="form_class">
            <input type="text" name="description" id="description" placeholder="Thoughts?"/>
            <input type="text" name="location" id="location" placeholder="Where did you eat this at?"/>
            <input type="text" name="name" id="name" placeholder="What did you order?"/>
            <input type="text" name="culture" id="culture" placeholder="Culture?"/>
            <input type="text" name="price" id="price" placeholder="Price?"/>
            <button class="cropit-save" name="submit_class" id="btn_class" value="Submit by Class">Finished!</button>
          </form>
      </div>

    </div>

app/views/users/profile.html.erb
<nav id="navfeed">

  <div class="feed-title"><strong>Savorit</strong>
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
  <center>  <%= link_to posts_path(id: @current_user.id) do %><i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
  <center> <%= link_to explore_path do%><i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center> <%= link_to new_post_path(id: @current_user.id) do %><i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
  <center>   <%= link_to cart_path(id: @current_user.id) do %><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

    <div class="icons">
      <center> <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
    </div>
</div>
<div class="profilecontainer">
<div class="profileheader">
  <center>
<p><%= image_tag attachment_url(@user, :photo, :fill, 50, 50, format: "jpg"), class:"pp" %>

<%= @user.first_name %>
<%= @user.last_name %>
@<%= @user.user_name %>
<% if @current_user && @current_user.following?(@user)%>
<div class="followbtn"><em><%= link_to "Following", unfollow_path(id: @user.id), class:'follows'%></em></div>
<% elsif @current_user %>
<div class="followbtn"><em><center><%= link_to "Follow", follow_path(id: @user.id), class:'follows'%></center></em></div>
<% end %>
</p>
</center>
</div>

<div class="profilepiccontainer">
<% @user.posts.each do |f| %>
<div class="profileimages">
<%= image_tag attachment_url(f, :photo, :fill, 300, 370, format: "jpg"), class:"feedpic" %>
</div>
<%end %>
</div>
</div>