config/routes.rb
Rails.application.routes.draw do

  mount Payola::Engine => '/payola', as: :payola

  root 'welcome#welcome'

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#delete', as: :sign_out

  get "/users/new" => 'users#new', as: :sign_up
  post "/users/new" => 'users#create', as: :users
  get '/users/:id/feed' => 'users#feed', as: :posts
  get '/users/:id/feed/upload' => 'users#new_post', as: :new_post
  post 'users/:id/feed' => 'users#create_post'
  post 'users/:id/feed' => 'users#create_comment', as: :comments
  get '/users/explore/:id' => 'users#profile', as: :user
  get '/users/explore' => 'users#explore', as: :explore
  post 'users/explore/:id/follow' => 'following#create', as: :follow
  post 'users/explore/:id/unfollow' => 'following#delete', as: :unfollow

  get '/users/:id/orders/index' => 'orders#index', as: :orders
  get '/users/:id/orders/:id' => 'orders#show', as: :order

  get 'posts/:id' => 'posts#show', as: :post
  post '/users/:id/cart' => 'carts#add_to_cart', as: :add_to_cart
  get '/users/:id/cart' => 'carts#view', as: :cart
  delete '/users/:id/cart' => 'carts#remove_from_cart', as: :remove_from_cart

  get '/users/:id/checkout'=>'checkout#start', as: :checkout
  post '/users/:id/checkout'=> 'checkout#process_payment', as: :process_payment
  get '/users/:id/receipt/:id' => 'checkout#receipt', as: :receipt

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def total_price
     order_items.map { |order_item| order_item.total_price }.sum
  end

  def description
   "Order ##{id}. #{order_items.map {|oi| oi.post.name}.join(", ")}"
  end
  
  def total_price_in_cents
    (total_price * 100).to_i
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :post

  def total_price
    quantity * price 
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :order_items
  attachment :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :orders
  has_many :comments
  acts_as_followable
  acts_as_follower
  attachment :photo
  has_secure_password
  validates :first_name, :last_name, :user_name, :email, :password, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action do
      if @current_user.nil?
        redirect_to sign_in_path
      end
    end

    def remove_from_cart
      order = Order.find_by status: 'cart', user_id: @current_user.id
      @post = Post.find_by id: params[:post_id]

      order_item = OrderItem.find_by order_id: order.id, post_id: @post.id
      order_item.destroy

      redirect_to cart_path
    end

    def add_to_cart


      @post = Post.find_by id: params[:post_id]

      order = Order.find_by status: 'cart', user_id: @current_user.id

      if order.nil?
        order = Order.new
        order.user = @current_user
        order.save!
      end

      order_item = OrderItem.find_by order_id: order.id, post_id: @post.id
      if order_item.present?
        order_item.quantity = order_item.quantity + 1
      else
        order_item = OrderItem.new
        order_item.order = order
        order_item.post = @post # what do I replace this with? It's nil
        order_item.price = @post.price
        order_item.shipping_cost = 0
        order_item.quantity = 1
      end
      order_item.save!
      redirect_to cart_path

    end

    def view

      @order = Order.find_by status: 'cart', user_id: @current_user.id
    end
  end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action do
      if @current_user.nil?
        redirect_to sign_in_path
      end
    end

    def start
      @order = Order.find_by status: 'cart', user_id: @current_user.id
    end

    def process_payment
      @order = Order.find_by status: 'cart', user_id: @current_user.id
      @user=User.first
      card_token = params[:stripeToken]

      Stripe.api_key = "sk_test_xIGhTi9JGwC0H65Tq1KdFEJE"

      Stripe::Charge.create(
        :amount => @order.total_price_in_cents,
        :currency => "usd",
        :source => card_token,
        :description => @order.description
      )

      if @order.update status: 'pending'
        InstructionsMailer.instructions_email(@user).deliver
      redirect_to receipt_path(id: @order.id)
      else
        render :new
      end
    end

    def receipt
      @order = Order.find_by! id: params[:id], user_id: @current_user.id
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where("status !=?", 'cart')
  end

  def show
    @order = Order.find_by id: params[:id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    email = params[:email]
    password = params[:password]
    user = User.find_by email: email
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to posts_path(id: user.id)
    else
      render :new
  end
end

def delete
  session[:user_id] = nil
    redirect_to root_path
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def feed
    @post=Post.new
    @user= User.find_by id: params[:id]
    @current_user = User.find_by id: session[:user_id]
    @users=User.all
    if @current_user && @current_user.following_users.present?
    follower_ids = @current_user.following_users.pluck(:id)
    all_ids = follower_ids << @current_user.id
    @posts = Post.where(user_id: all_ids).order("created_at DESC")
  else
    @posts = Post.all.order("created_at desc")
  end
  end

  def new_post
@post=Post.new
end

def create_post
  @post = Post.new params.require(:post).permit(:description,:user_id, :view_count, :culture, :type, :location, :photo, :name, :price,:delivery_cost, :inventory)
  @post.user=@current_user
  if @post.save
    redirect_to posts_path(id: @current_user.id)
  else
    flash.now[:alert] = "Looks like your Missing Something"
    render :new
  end
end

  def profile
    @user= User.find_by id: params[:id]
    @posts=Post.all
  end

  def new
  end

  def explore
    @user= User.find_by id: params[:id]
    @posts=Post.all
  end

  def new
  @user=User.new
  end

  def create
  @user = User.new params.require(:user).permit(:email, :password, :first_name, :last_name, :user_name, :city, :address, :photo)
  if @user.save
   session[:user_id] = @user.id
  redirect_to posts_path(id: @user.id)
  else
   flash.now[:alert] = "Something is Missing"
  render:new
  end
  end

  def create_comment
    @post = Post.find_by id: params[:id]
    @comment = Comment.new params.require(:comment).permit(:comment)
    @comment.post_id = @post.id

    if @comment.save
      redirect_to explore_path
    else
      render :view
    end
  end


  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/view.html.erb
<nav id="navfeed">

  <div class="feed-title"><strong>Savorit</strong>
  </div>
  <div class="feed-subtitle">
    Feed The Craving
  </div>
</nav>

<div id="footer">

  <div class="icons">
  <center>  <%= link_to posts_path(id: @current_user.id) do %><i class="fa fa-home fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
  <center> <%= link_to explore_path do%><i class="fa fa-compass fa-2x" aria-hidden="true"></i><%end%></center>
  </div>

  <div class="icons">
    <center> <%= link_to new_post_path(id: @current_user.id) do %><i class="fa fa-camera-retro fa-2x"></i><%end%></center>
  </div>

  <div class="icons">
  <center>   <%= link_to cart_path(id: @current_user.id) do %><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><%end %></center>
  </div>

    <div class="icons">
      <center> <%= link_to sign_out_path do %>
      <i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><%end%></center>
    </div>
</div>
<h1 class="shopping-cart"> Shopping Cart </h1>
<ul>

  <li>
    <strong>Total Price: </strong>

    $<%= @order.total_price %>

  </li>
</ul>
<div class="cartitems">
<div class="carthead">Items</div>
<% @order.order_items.each do |f| %>
<div class="cartinfo">
<%= f.post.name %>
<%= f.quantity %> at <%= f.price %>
 <%= link_to 'Remove Item', remove_from_cart_path(post_id: f.post_id), method: :delete, class:"removeitem"%><p>
Total Price:  <%= number_to_currency f.total_price %>
</p>
</div>
<%= link_to 'Ready to Eat?', checkout_path, class:"checkout" %>
</div>
<%end %>

app/views/welcome/welcome.html.erb
<nav>
  <p class="welcome-title">
    Savor it
  </p>
  <div class="login-container">
    <p id="login"><%= link_to sign_in_path, class:"login" do %>
      <button id="signin">
        Sign In</button>
      <% end %></p>
    <p><%= link_to sign_up_path, class:"login" do %>
      <button id="signup">
        Sign Up</button><% end %></p>
  </div>
</nav>
<div class="welcome-image-container">
  <%= image_tag 'shakeshack.jpg', class:'welcome-image' %>
  <p class="welcome-image-text">
    Find local restaurants your friends are eating at and order it straight to your doorstep.
  </p>
</div>
<div class="how-to">
  <div class="heading">
    <center>
      <p class=heading-title>How to Savor It
      </p>
    </center>
    <center>
      <p class="how-subhead">Exploring food has never been easier, Having it in front of you has never been faster.
      </p>
    </center>
  </div>
  <center>
    <div class="directions-container">
      <div class="directions" style="margin-left:20px;">
        <center>
          <i class="fa fa-search fa-3x" aria-hidden="true"></i>
          <p class="subhead">The Search
          </p>
          <p class="info">Connect with friends and look through what everyone is eating.</p>
        </center>
      </div>
      <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i>
      <div class="directions">
        <i class="fa fa-check-circle fa-3x" aria-hidden="true"></i>
        <p class="subhead">The Find
        </p>
        <p class="info">Decide what you want to eat and checkout.</p>
      </div>
      <i class="fa fa-arrow-circle-right fa-2x" aria-hidden="true"></i>
      <div class="directions">
        <i class="fa fa-car fa-3x" aria-hidden="true"></i>
        <p class="subhead">The Delivery
        </p>
        <p class="info">
          Get comfy because the food comes to you.</p>
      </div>
    </div>
  </center>
</div>
<div class="munch-container">
  <p class='munch-title'>
    Munches and Mumbles
  </p>
  <div class="review-container">

    <div class="review">
      <%= image_tag 'noor.png', class: 'reviewer-image' %>
      <p>
        @Savorit You make fat kids on the inside and outside happy. Thanks!
      </p>
      <p style="font-weight:bold;">
        @Noora_The_Explora
      </p>
    </div>

    <div class="review">
      <%= image_tag 'zaki.jpg', class: 'reviewer-image' %>
      <p>
        @Savorit has satisfied my late night cravings too many times. #FatKidsUnite
      </p>
      <p style="font-weight:bold;">
        @Zbreezy
      </p>
    </div>

    <div class="review">
      <%= image_tag 'sarah.jpg', class: 'reviewer-image' %>
      <p>
        Just stalking what my friends eat because food is my one true love. Time to order thanks @Savorit
      </p>
      <p style="font-weight:bold;">
        @SK_the_Don
      </p>
    </div>

    <div class="review">
      <%= image_tag 'mohsin.jpg', class: 'reviewer-image' %>
      <p>
        The daily struggle of wondering what to eat but as usual @Savorit came to the rescue. #LifeChanging
      </p>
      <p style="font-weight:bold;">
        @Hungry_Beard
      </p>
    </div>

  </div>

</div>
<div class="Why-container">
  <p class="why-title">
    Why find food with SavorIt
  </p>
  <div class="block-container">
  <div class="block">
    <i class="fa fa-diamond fa-3x" aria-hidden="true"></i>
    <p class="why-title">
      Diamond in the Rough
      </p>
    <p class="why-info">
      Find rare places to eat
    </p>
  </div>

  <div class="block">
    <i class="fa fa-thumbs-o-up fa-3x" aria-hidden="true"></i>
    <p class="why-title">
      Better Finds
      </p>
    <p class="why-info">
      Your friends give recommendations, thats the best part.
    </p>
  </div>

  <div class="block">
    <i class="fa fa-cutlery fa-3x" aria-hidden="true"></i>
    <p class="why-title">
      Eat Good
      </p>
    <p class="why-info">
      Comfortably eat at home knowing you moved 0.0 inches for this food.
    </p>
  </div>
</div>
</div>
  <div class="about-container">
    <div class="about-title">
      About SavorIt
    </div>
    <div class="about-info">
      Ever unsure about what to eat? Always scrolling through Yelp not knowing what to truly expect? Fear not, SavorIt is here</br></br> SavorIt helps you find and order food from wherever you are based on what your friends are ordering. How it works: You scroll through your food feed and see what your friends are eating. When you find what you're looking for, you can order what your friends are eating straight to any address you want in your local area.
    </div>
  </div>
<div class="footer">
  <p>&copy; SavorIt All Rights Reserved | created by: Zaki Ahmed </br>Check out more work at <a href="www.zakiahmed.org">www.zakiahmed.org</a></p>
</div>